import Head from "next/head";
import {Inter} from "next/font/google";
import {useEffect, useState} from "react";
import Header from "@/pages/components/Header";
import Slide from "@/pages/components/Slide";

const inter = Inter({subsets: ["latin"]});


export default function Home() {
  const [fileList, setFileList] = useState<string[][][]>([])
  const [isVideoLoaded, setIsVideoLoaded] = useState(false)
  const [loadedData, setLoadedData] = useState(0)


  useEffect(() => {
    fetch("/api/getPublicList").then(res => res.json()).then(res => {
      for (let i = 0; i < res.files.length; i += 5) {
        let chunk = res.files.slice(i, i + 5);
        setFileList(prevState => [...prevState, chunk])
      }
    })
  }, []);

  const handleLoadData = () => {
    setLoadedData(prevState => prevState + 1)
  }

  console.log(isVideoLoaded)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Header setIsVideoLoaded={setIsVideoLoaded}/>
      <main className={`${inter.className}`}>
        {fileList.map((fileGroup, index) => {
          const threshold = index * 5;
          if (fileGroup.length > 0 && isVideoLoaded && loadedData >= threshold) {
            return fileGroup.map(item => (
              <Slide key={item[0]} setIsLoadData={handleLoadData} fileNames={item} />
            ));
          }
          return null;
        })}
      </main>
    </>
  );
}
